### ISSUE TITLE
MWE of CAM code

### ISSUE THREAD

**Issue by TomMelt** [DataWaveProject/nonlocal_gwfluxes#3]
@amangupta2 to provide a minimum worked example of CAM so that @j-emberton and @TomMelt can run it.

**Comment by TomMelt** [comment]
For now we are using the model from Qiang et al. However @amangupta2 will reach out to collaborators to find a compset / configuration for the resolution we intend to run at.

**Comment by amangupta2** [comment]
I have sent an email to Martina outlining the problem. Hoping for her response soon.

**Comment by TomMelt** [comment]
Seeming as we already have a working example running on `derecho` I will mark this as closed.
